import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  English: {
    home: "Home",
    about: "About",
    jobs: "Jobs",
    contact: "Contact",
    feedback: "Feedback",
    login: "Login",
    signup: "Sign Up",
    hero_title: "Build Your Dream Career",
    hero_subtitle: "Connect with top recruiters and discover opportunities that match your skills perfectly.",
    why_choose: "Why Choose CareerNest?",
    testimonials: "What Our Users Say",
    about_text: "CareerNest is a state-of-the-art, AI-powered recruitment platform designed to connect top-tier talent with industry-leading companies. We leverage advanced machine learning to build ATS-optimized resumes and facilitate precise candidate-to-job matching. Our mission is to bridge the gap between ambition and opportunity by providing an intelligent, seamless, and professional job search experience for everyone.",
    feature_ai_desc: "Our intelligent algorithms match your unique skills with the perfect job opportunities automatically.",
    feature_ats_desc: "Create professional, ATS-friendly resumes that stand out to recruiters and pass automated screenings.",
    feature_recruiter_desc: "Connect directly with hiring managers and top recruiters from leading companies.",
    // Auth & Forms
    full_name: "Full Name",
    email_addr: "Email Address",
    mobile_num: "Mobile Number",
    password: "Password",
    role_label: "I want to...",
    find_job: "Find a Job",
    post_job_role: "Post a Job",
    prove_human: "Prove you are human. Enter the code:",
    agree_terms: "I agree to the",
    privacy_policy: "Privacy Policy",
    terms_cond: "Terms & Conditions",
    already_account: "Already have an account?",
    sign_in_here: "Sign in here",
    dont_account: "Don't have an account?",
    create_free: "Create one for free",
    welcome_back: "Welcome Back",
    login_subtitle: "Login to your CareerNest account",
    create_account: "Create Account",
    join_future: "Join the future of job hunting",
    // Dashboard
    seeker_dash: "Seeker Dashboard",
    recruiter_dash: "Recruiter Dashboard",
    applied_jobs: "Applied Jobs",
    posted_jobs: "Posted Jobs",
    profile_settings: "Profile Settings",
    active_applications: "Active Applications",
    total_postings: "Total Postings",
    footer_desc: "Empowering professionals to build their dream careers through AI-driven insights and direct recruiter connections.",
    search_jobs: "Search Jobs",
    notifications: "Notifications",
    theme: "Theme",
    dashboard: "Dashboard",
    post_job: "Post a Job",
    resume_builder: "Resume Builder",
    logout: "Logout",
    ready_career: "Ready to accelerate your career?",
    join_today: "Join CareerNest Today",
    quick_links: "Quick Links",
    contact_us: "Contact Us",
    location: "Our Location",
    chat_assistant: "AI Assistant & Support",
    chat_placeholder: "Type a message...",
    captcha_placeholder: "Enter verification code",
    chat_send: "Send",
    // Common
    loading: "Loading...",
    error: "Error",
    success: "Success",
    // Testimonials
    testi_1_name: "Sarah Jenkins",
    testi_1_role: "Software Engineer",
    testi_1_text: "CareerNest helped me land my dream job in just two weeks! The AI matching is incredibly accurate.",
    testi_2_name: "David Chen",
    testi_2_role: "Product Manager",
    testi_2_text: "The resume builder is top-notch. It highlighted my skills in a way that got me multiple interview calls.",
    testi_3_name: "Emily Rodriguez",
    testi_3_role: "UX Designer",
    testi_3_text: "I love the clean interface and how easy it is to track my applications. Highly recommend to any job seeker!",
    testi_4_name: "Michael Chang",
    testi_4_role: "Data Scientist",
    testi_4_text: "The personalized job recommendations saved me countless hours of searching. Found an amazing role within days.",
    testi_5_name: "Jessica Taylor",
    testi_5_role: "Marketing Specialist",
    testi_5_text: "Direct recruiter access is a game changer. I bypassed the standard application black hole completely.",
    testi_6_name: "James Wilson",
    testi_6_role: "Frontend Developer",
    testi_6_text: "Using CareerNest gave me the edge I needed. The ATS resume optimization specifically got me past initial screening.",
    address: "Jalandhar - Delhi, GT Road, Phagwara, Punjab 144411",
    rights_reserved: "CareerNest. All rights reserved."
  },
  Hindi: {
    home: "होम",
    about: "हमारे बारे में",
    jobs: "नौकरियां",
    contact: "संपर्क करें",
    feedback: "फीडबैक",
    login: "लॉगिन",
    signup: "साइन अप",
    hero_title: "अपना सपनों का करियर बनाएं",
    hero_subtitle: "शीर्ष नियोक्ताओं से जुड़ें और उन अवसरों की खोज करें जो आपके कौशल से मेल खाते हैं।",
    why_choose: "करियरनेस्ट क्यों चुनें?",
    testimonials: "हमारे उपयोगकर्ता क्या कहते हैं",
    about_text: "करियरनेस्ट एक अत्याधुनिक, एआई-संचालित भर्ती मंच है जिसे शीर्ष स्तरीय प्रतिभाओं को उद्योग की अग्रणी कंपनियों के साथ जोड़ने के लिए डिज़ाइन किया गया है। हम एटीएस-अनुकूलित रिज्यूमे बनाने और सटीक उम्मीदवार-से-नौकरी मिलान की सुविधा के लिए उन्नत मशीन लर्निंग का लाभ उठाते हैं। हमारा मिशन सभी के लिए एक बुद्धिमान, निर्बाध और पेशेवर नौकरी खोज अनुभव प्रदान करके महत्वाकांक्षा और अवसर के बीच की खाई को पाटना है।",
    feature_ai_desc: "हमारे बुद्धिमान एल्गोरिदम आपके अद्वितीय कौशल को स्वचालित रूप से सही नौकरी के अवसरों के साथ मिलाते हैं।",
    feature_ats_desc: "पेशेवर, एटीएस-अनुकूल रिज्यूमे बनाएं जो नियोक्ताओं के लिए अलग दिखें और स्वचालित स्क्रीनिंग पास करें।",
    feature_recruiter_desc: "अग्रणी कंपनियों के हायरिंग मैनेजरों और शीर्ष भर्तीकर्ताओं के साथ सीधे जुड़ें।",
    footer_desc: "एआई-संचालित अंतर्दृष्टि और प्रत्यक्ष भर्ती कनेक्शन के माध्यम से पेशेवरों को उनके सपनों का करियर बनाने के लिए सशक्त बनाना।",
    search_jobs: "नौकरियां खोजें",
    notifications: "सूचनाएं",
    theme: "थीम",
    dashboard: "डैशबोर्ड",
    post_job: "नौकरी पोस्ट करें",
    resume_builder: "रिज्यूमे बिल्डर",
    logout: "लॉगआउट",
    ready_career: "अपने करियर को गति देने के लिए तैयार हैं?",
    join_today: "आज ही करियरनेस्ट से जुड़ें",
    quick_links: "त्वरित लिंक",
    contact_us: "संपर्क करें",
    location: "हमारा स्थान",
    support_online: "ऑनलाइन",
    chat_assistant: "एआई सहायक और सहायता",
    chat_placeholder: "संदेश टाइप करें...",
    captcha_placeholder: "सत्यापन कोड दर्ज करें",
    chat_send: "भेजें",
    // Auth & Forms (Hindi)
    full_name: "पूरा नाम",
    email_addr: "ईमेल पता",
    mobile_num: "मोबाइल नंबर",
    password: "पासवर्ड",
    role_label: "मैं चाहता हूँ...",
    find_job: "नौकरी ढूँढना",
    post_job_role: "नौकरी पोस्ट करना",
    prove_human: "साबित करें कि आप इंसान हैं। कोड दर्ज करें:",
    agree_terms: "मैं सहमत हूँ",
    privacy_policy: "गोपनीयता नीति",
    terms_cond: "नियम और शर्तें",
    already_account: "क्या आपके पास पहले से एक खाता है?",
    sign_in_here: "यहाँ लॉगिन करें",
    dont_account: "खाता नहीं है?",
    create_free: "मुफ्त में बनाएँ",
    welcome_back: "वापसी पर स्वागत है",
    login_subtitle: "अपने करियरनेस्ट खाते में लॉगिन करें",
    create_account: "खाता बनाएँ",
    join_future: "नौकरी खोजने के भविष्य से जुड़ें",
    // Dashboard (Hindi)
    seeker_dash: "सीकर डैशबोर्ड",
    recruiter_dash: "रिक्रूटर डैशबोर्ड",
    applied_jobs: "आवेदन की गई नौकरियां",
    posted_jobs: "पोस्ट की गई नौकरियां",
    profile_settings: "प्रोफ़ाइल सेटिंग्स",
    active_applications: "सक्रिय आवेदन",
    total_postings: "कुल पोस्टिंग",
    // Common (Hindi)
    loading: "लोड हो रहा है...",
    error: "त्रुटि",
    success: "सफलता",
    // Testimonials (Hindi)
    testi_1_name: "सारा जेनकिंस",
    testi_1_role: "सॉफ्टवेयर इंजीनियर",
    testi_1_text: "करियरनेस्ट ने मुझे सिर्फ दो हफ्तों में मेरे सपनों की नौकरी पाने में मदद की! एआई मैचिंग अविश्वसनीय रूप से सटीक है।",
    testi_2_name: "डेविड चेन",
    testi_2_role: "प्रोडक्ट मैनेजर",
    testi_2_text: "रिज्यूमे बिल्डर बेहतरीन है। इसने मेरे कौशल को इस तरह से उजागर किया कि मुझे कई इंटरव्यू कॉल आए।",
    testi_3_name: "एमिली रोड्रिगेज",
    testi_3_role: "यूएक्स डिजाइनर",
    testi_3_text: "मुझे स्वच्छ इंटरफ़ेस और अपने आवेदनों को ट्रैक करना कितना आसान है, यह पसंद है। किसी भी नौकरी चाहने वाले को अत्यधिक अनुशंसा करते हैं!",
    testi_4_name: "माइकल चांग",
    testi_4_role: "डेटा साइंटिस्ट",
    testi_4_text: "व्यक्तिगत नौकरी की सिफारिशों ने मुझे खोजने के अनगिनत घंटे बचाए। कुछ ही दिनों में एक अद्भुत भूमिका मिली।",
    testi_5_name: "जेसिका टेलर",
    testi_5_role: "मार्केटिंग विशेषज्ञ",
    testi_5_text: "प्रत्यक्ष भर्तीकर्ता पहुंच एक गेम चेंजर है। मैंने मानक आवेदन ब्लैक होल को पूरी तरह से बायपास कर दिया।",
    testi_6_name: "जेम्स विल्सन",
    testi_6_role: "फ्रंटएंड डेवलपर",
    testi_6_text: "करियरनेस्ट का उपयोग करने से मुझे वह बढ़त मिली जिसकी मुझे आवश्यकता थी। एटीएस रिज्यूमे अनुकूलन ने मुझे प्रारंभिक स्क्रीनिंग से पार करा दिया।",
    address: "जालंधर - दिल्ली, जीटी रोड, फगवाड़ा, पंजाब 144411",
    rights_reserved: "करियरनेस्ट। सर्वाधिकार सुरक्षित।"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('English');

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
